apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ilyin-website-ingress
  namespace: ilyin-website
spec:
  rules:
  - host: www.ilyin.website
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: www-ilyin-website-service
              port:
                number: 8080